#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestQuestionnaireSystem
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbTestQuestionnaire")]
	public partial class DataClassesTestQuestionnaireDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblTeacher(tblTeacher instance);
    partial void UpdatetblTeacher(tblTeacher instance);
    partial void DeletetblTeacher(tblTeacher instance);
    partial void InserttblSection(tblSection instance);
    partial void UpdatetblSection(tblSection instance);
    partial void DeletetblSection(tblSection instance);
    partial void InserttblStudent(tblStudent instance);
    partial void UpdatetblStudent(tblStudent instance);
    partial void DeletetblStudent(tblStudent instance);
    #endregion
		
		public DataClassesTestQuestionnaireDataContext() : 
				base(global::TestQuestionnaireSystem.Properties.Settings.Default.dbTestQuestionnaireConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesTestQuestionnaireDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesTestQuestionnaireDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesTestQuestionnaireDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesTestQuestionnaireDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblQuestion> tblQuestions
		{
			get
			{
				return this.GetTable<tblQuestion>();
			}
		}
		
		public System.Data.Linq.Table<tblTeacher> tblTeachers
		{
			get
			{
				return this.GetTable<tblTeacher>();
			}
		}
		
		public System.Data.Linq.Table<tblScore> tblScores
		{
			get
			{
				return this.GetTable<tblScore>();
			}
		}
		
		public System.Data.Linq.Table<tblSection> tblSections
		{
			get
			{
				return this.GetTable<tblSection>();
			}
		}
		
		public System.Data.Linq.Table<tblStudent> tblStudents
		{
			get
			{
				return this.GetTable<tblStudent>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_addQuestion")]
		public int sp_addQuestion([global::System.Data.Linq.Mapping.ParameterAttribute(Name="No", DbType="Int")] System.Nullable<int> no, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Question", DbType="NVarChar(80)")] string question, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Answer", DbType="NVarChar(80)")] string answer, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Choice1", DbType="NVarChar(80)")] string choice1, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Choice2", DbType="NVarChar(80)")] string choice2, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Choice3", DbType="NVarChar(80)")] string choice3, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Section_Grade", DbType="VarChar(30)")] string section_Grade, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Section_name", DbType="VarChar(30)")] string section_name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="T_ID", DbType="VarChar(30)")] string t_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), no, question, answer, choice1, choice2, choice3, section_Grade, section_name, t_ID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_viewTeacher")]
		public ISingleResult<sp_viewTeacherResult> sp_viewTeacher()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_viewTeacherResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_addScore")]
		public int sp_addScore([global::System.Data.Linq.Mapping.ParameterAttribute(Name="S_ID", DbType="VarChar(30)")] string s_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="T_ID", DbType="VarChar(30)")] string t_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="S_LastName", DbType="NVarChar(30)")] string s_LastName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="S_FirstName", DbType="NVarChar(30)")] string s_FirstName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Section_Grade", DbType="VarChar(30)")] string section_Grade, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Section_name", DbType="VarChar(30)")] string section_name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Correct", DbType="VarChar(30)")] string correct, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Wrong", DbType="VarChar(30)")] string wrong)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), s_ID, t_ID, s_LastName, s_FirstName, section_Grade, section_name, correct, wrong);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_addSection")]
		public int sp_addSection([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Section_ID", DbType="VarChar(30)")] string section_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Section_name", DbType="VarChar(30)")] string section_name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Section_Grade", DbType="VarChar(30)")] string section_Grade, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="T_ID", DbType="VarChar(30)")] string t_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="T_Name", DbType="VarChar(30)")] string t_Name)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), section_ID, section_name, section_Grade, t_ID, t_Name);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_addStudent")]
		public int sp_addStudent([global::System.Data.Linq.Mapping.ParameterAttribute(Name="S_ID", DbType="VarChar(30)")] string s_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="S_Username", DbType="VarChar(30)")] string s_Username, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="S_Password", DbType="VarChar(30)")] string s_Password, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="S_LastName", DbType="NVarChar(30)")] string s_LastName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="S_FirstName", DbType="NVarChar(30)")] string s_FirstName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Section_Grade", DbType="VarChar(30)")] string section_Grade, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Section_name", DbType="VarChar(30)")] string section_name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="T_ID", DbType="VarChar(30)")] string t_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="T_name", DbType="VarChar(30)")] string t_name)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), s_ID, s_Username, s_Password, s_LastName, s_FirstName, section_Grade, section_name, t_ID, t_name);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_addTeacher")]
		public int sp_addTeacher([global::System.Data.Linq.Mapping.ParameterAttribute(Name="T_ID", DbType="VarChar(30)")] string t_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="T_Username", DbType="VarChar(30)")] string t_Username, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="T_Password", DbType="VarChar(30)")] string t_Password, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="T_LastName", DbType="NVarChar(30)")] string t_LastName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="T_FirstName", DbType="NVarChar(30)")] string t_FirstName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="T_UserType", DbType="VarChar(30)")] string t_UserType)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), t_ID, t_Username, t_Password, t_LastName, t_FirstName, t_UserType);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_countQuez")]
		public ISingleResult<sp_countQuezResult> sp_countQuez([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Section_Grade", DbType="VarChar(30)")] string section_Grade, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Section_name", DbType="VarChar(30)")] string section_name)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), section_Grade, section_name);
			return ((ISingleResult<sp_countQuezResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_deleteTeacher")]
		public int sp_deleteTeacher([global::System.Data.Linq.Mapping.ParameterAttribute(Name="T_LastName", DbType="NVarChar(30)")] string t_LastName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="T_FirstName", DbType="NVarChar(30)")] string t_FirstName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), t_LastName, t_FirstName);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_NameTeacher")]
		public ISingleResult<sp_NameTeacherResult> sp_NameTeacher([global::System.Data.Linq.Mapping.ParameterAttribute(Name="T_FirstName", DbType="VarChar(30)")] string t_FirstName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="T_LastName", DbType="VarChar(30)")] string t_LastName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), t_FirstName, t_LastName);
			return ((ISingleResult<sp_NameTeacherResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_retrieveID")]
		public ISingleResult<sp_retrieveIDResult> sp_retrieveID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="T_ID", DbType="VarChar(30)")] string t_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), t_ID);
			return ((ISingleResult<sp_retrieveIDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_retrieveIDStudent")]
		public ISingleResult<sp_retrieveIDStudentResult> sp_retrieveIDStudent([global::System.Data.Linq.Mapping.ParameterAttribute(Name="S_ID", DbType="VarChar(30)")] string s_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), s_ID);
			return ((ISingleResult<sp_retrieveIDStudentResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_retrieveInfoStudent")]
		public ISingleResult<sp_retrieveInfoStudentResult> sp_retrieveInfoStudent([global::System.Data.Linq.Mapping.ParameterAttribute(Name="S_LastName", DbType="NVarChar(30)")] string s_LastName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="S_FirstName", DbType="NVarChar(30)")] string s_FirstName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Section_Grade", DbType="VarChar(30)")] string section_Grade, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Section_name", DbType="VarChar(30)")] string section_name)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), s_LastName, s_FirstName, section_Grade, section_name);
			return ((ISingleResult<sp_retrieveInfoStudentResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_retrieveName")]
		public ISingleResult<sp_retrieveNameResult> sp_retrieveName([global::System.Data.Linq.Mapping.ParameterAttribute(Name="T_LastName", DbType="NVarChar(30)")] string t_LastName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="T_FirstName", DbType="NVarChar(30)")] string t_FirstName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), t_LastName, t_FirstName);
			return ((ISingleResult<sp_retrieveNameResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_RetrieveQuiz")]
		public ISingleResult<sp_RetrieveQuizResult> sp_RetrieveQuiz([global::System.Data.Linq.Mapping.ParameterAttribute(Name="No", DbType="Int")] System.Nullable<int> no, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Section_Grade", DbType="VarChar(30)")] string section_Grade, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Section_name", DbType="VarChar(30)")] string section_name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="T_ID", DbType="VarChar(30)")] string t_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), no, section_Grade, section_name, t_ID);
			return ((ISingleResult<sp_RetrieveQuizResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_retrieveScore")]
		public ISingleResult<sp_retrieveScoreResult> sp_retrieveScore([global::System.Data.Linq.Mapping.ParameterAttribute(Name="S_ID", DbType="VarChar(30)")] string s_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), s_ID);
			return ((ISingleResult<sp_retrieveScoreResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_retrieveSection")]
		public ISingleResult<sp_retrieveSectionResult> sp_retrieveSection([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Section_name", DbType="VarChar(30)")] string section_name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Section_Grade", DbType="VarChar(30)")] string section_Grade, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="T_Name", DbType="VarChar(30)")] string t_Name)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), section_name, section_Grade, t_Name);
			return ((ISingleResult<sp_retrieveSectionResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_retrieveStudent")]
		public ISingleResult<sp_retrieveStudentResult> sp_retrieveStudent([global::System.Data.Linq.Mapping.ParameterAttribute(Name="S_Username", DbType="VarChar(30)")] string s_Username, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="S_Password", DbType="VarChar(30)")] string s_Password)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), s_Username, s_Password);
			return ((ISingleResult<sp_retrieveStudentResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_retrieveTeacher")]
		public ISingleResult<sp_retrieveTeacherResult> sp_retrieveTeacher([global::System.Data.Linq.Mapping.ParameterAttribute(Name="T_Username", DbType="VarChar(30)")] string t_Username, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="T_Password", DbType="VarChar(30)")] string t_Password)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), t_Username, t_Password);
			return ((ISingleResult<sp_retrieveTeacherResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_retrieveUsernameStudent")]
		public ISingleResult<sp_retrieveUsernameStudentResult> sp_retrieveUsernameStudent([global::System.Data.Linq.Mapping.ParameterAttribute(Name="S_Username", DbType="VarChar(30)")] string s_Username)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), s_Username);
			return ((ISingleResult<sp_retrieveUsernameStudentResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_retrieveUsernameTeacher")]
		public ISingleResult<sp_retrieveUsernameTeacherResult> sp_retrieveUsernameTeacher([global::System.Data.Linq.Mapping.ParameterAttribute(Name="T_Username", DbType="VarChar(30)")] string t_Username)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), t_Username);
			return ((ISingleResult<sp_retrieveUsernameTeacherResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_searchQuestion")]
		public ISingleResult<sp_searchQuestionResult> sp_searchQuestion([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string key, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Section_Grade", DbType="VarChar(30)")] string section_Grade, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Section_name", DbType="VarChar(30)")] string section_name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="T_ID", DbType="VarChar(30)")] string t_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), key, section_Grade, section_name, t_ID);
			return ((ISingleResult<sp_searchQuestionResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_searchS")]
		public ISingleResult<sp_searchSResult> sp_searchS([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string key)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), key);
			return ((ISingleResult<sp_searchSResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_searchStudent")]
		public ISingleResult<sp_searchStudentResult> sp_searchStudent([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string key)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), key);
			return ((ISingleResult<sp_searchStudentResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_searchT")]
		public ISingleResult<sp_searchTResult> sp_searchT([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string key)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), key);
			return ((ISingleResult<sp_searchTResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_sectionID")]
		public ISingleResult<sp_sectionIDResult> sp_sectionID()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_sectionIDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_SelectScore")]
		public ISingleResult<sp_SelectScoreResult> sp_SelectScore([global::System.Data.Linq.Mapping.ParameterAttribute(Name="S_ID", DbType="VarChar(30)")] string s_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), s_ID);
			return ((ISingleResult<sp_SelectScoreResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_selectSection")]
		public ISingleResult<sp_selectSectionResult> sp_selectSection([global::System.Data.Linq.Mapping.ParameterAttribute(Name="T_ID", DbType="VarChar(30)")] string t_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), t_ID);
			return ((ISingleResult<sp_selectSectionResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_selectSectioninGrade")]
		public ISingleResult<sp_selectSectioninGradeResult> sp_selectSectioninGrade([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Section_Grade", DbType="VarChar(30)")] string section_Grade, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="T_ID", DbType="VarChar(30)")] string t_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), section_Grade, t_ID);
			return ((ISingleResult<sp_selectSectioninGradeResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_SelectTeacher")]
		public ISingleResult<sp_SelectTeacherResult> sp_SelectTeacher()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_SelectTeacherResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_StudentID")]
		public ISingleResult<sp_StudentIDResult> sp_StudentID()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_StudentIDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_teacherID")]
		public ISingleResult<sp_teacherIDResult> sp_teacherID()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_teacherIDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_updateQuiz")]
		public int sp_updateQuiz([global::System.Data.Linq.Mapping.ParameterAttribute(Name="No", DbType="Int")] System.Nullable<int> no, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Question", DbType="NVarChar(80)")] string question, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Answer", DbType="NVarChar(80)")] string answer, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Choice1", DbType="NVarChar(80)")] string choice1, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Choice2", DbType="NVarChar(80)")] string choice2, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Choice3", DbType="NVarChar(80)")] string choice3, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Section_Grade", DbType="VarChar(30)")] string section_Grade, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Section_name", DbType="VarChar(30)")] string section_name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="T_ID", DbType="VarChar(30)")] string t_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), no, question, answer, choice1, choice2, choice3, section_Grade, section_name, t_ID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_updateScore")]
		public int sp_updateScore([global::System.Data.Linq.Mapping.ParameterAttribute(Name="S_ID", DbType="VarChar(30)")] string s_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Correct", DbType="VarChar(30)")] string correct, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Wrong", DbType="VarChar(30)")] string wrong)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), s_ID, correct, wrong);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_updateSection")]
		public int sp_updateSection([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Section_ID", DbType="VarChar(30)")] string section_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Section_name", DbType="VarChar(30)")] string section_name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Section_Grade", DbType="VarChar(30)")] string section_Grade, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="T_ID", DbType="VarChar(30)")] string t_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="T_Name", DbType="VarChar(30)")] string t_Name)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), section_ID, section_name, section_Grade, t_ID, t_Name);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_updateStudent")]
		public int sp_updateStudent([global::System.Data.Linq.Mapping.ParameterAttribute(Name="S_ID", DbType="VarChar(30)")] string s_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="S_Username", DbType="VarChar(30)")] string s_Username, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="S_Password", DbType="VarChar(30)")] string s_Password, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="S_LastName", DbType="NVarChar(30)")] string s_LastName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="S_FirstName", DbType="NVarChar(30)")] string s_FirstName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Section_Grade", DbType="VarChar(30)")] string section_Grade, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Section_name", DbType="VarChar(30)")] string section_name)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), s_ID, s_Username, s_Password, s_LastName, s_FirstName, section_Grade, section_name);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_updateStudent1")]
		public int sp_updateStudent1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="S_ID", DbType="VarChar(30)")] string s_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="S_Username", DbType="VarChar(30)")] string s_Username, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="S_Password", DbType="VarChar(30)")] string s_Password)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), s_ID, s_Username, s_Password);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_UpdateTeacher")]
		public int sp_UpdateTeacher([global::System.Data.Linq.Mapping.ParameterAttribute(Name="T_ID", DbType="VarChar(30)")] string t_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="T_Username", DbType="VarChar(30)")] string t_Username, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="T_Password", DbType="VarChar(30)")] string t_Password, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="T_LastName", DbType="NVarChar(30)")] string t_LastName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="T_FirstName", DbType="NVarChar(30)")] string t_FirstName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), t_ID, t_Username, t_Password, t_LastName, t_FirstName);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_viewQuestion")]
		public ISingleResult<sp_viewQuestionResult> sp_viewQuestion([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Section_Grade", DbType="VarChar(30)")] string section_Grade, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Section_name", DbType="VarChar(30)")] string section_name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="T_ID", DbType="VarChar(30)")] string t_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), section_Grade, section_name, t_ID);
			return ((ISingleResult<sp_viewQuestionResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ViewQuizNo")]
		public ISingleResult<sp_ViewQuizNoResult> sp_ViewQuizNo([global::System.Data.Linq.Mapping.ParameterAttribute(Name="No", DbType="Int")] System.Nullable<int> no, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Section_Grade", DbType="VarChar(30)")] string section_Grade, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Section_name", DbType="VarChar(30)")] string section_name)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), no, section_Grade, section_name);
			return ((ISingleResult<sp_ViewQuizNoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_viewScore")]
		public ISingleResult<sp_viewScoreResult> sp_viewScore([global::System.Data.Linq.Mapping.ParameterAttribute(Name="T_ID", DbType="VarChar(30)")] string t_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Section_name", DbType="VarChar(30)")] string section_name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Section_Grade", DbType="VarChar(30)")] string section_Grade)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), t_ID, section_name, section_Grade);
			return ((ISingleResult<sp_viewScoreResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_viewSection")]
		public ISingleResult<sp_viewSectionResult> sp_viewSection()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_viewSectionResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_viewStudent")]
		public ISingleResult<sp_viewStudentResult> sp_viewStudent([global::System.Data.Linq.Mapping.ParameterAttribute(Name="T_ID", DbType="VarChar(30)")] string t_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), t_ID);
			return ((ISingleResult<sp_viewStudentResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblQuestion")]
	public partial class tblQuestion
	{
		
		private System.Nullable<int> _No;
		
		private string _Section_Grade;
		
		private string _Section_name;
		
		private string _Question;
		
		private string _Answer;
		
		private string _Choice1;
		
		private string _Choice2;
		
		private string _Choice3;
		
		private string _T_ID;
		
		public tblQuestion()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_No", DbType="Int")]
		public System.Nullable<int> No
		{
			get
			{
				return this._No;
			}
			set
			{
				if ((this._No != value))
				{
					this._No = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section_Grade", DbType="VarChar(30)")]
		public string Section_Grade
		{
			get
			{
				return this._Section_Grade;
			}
			set
			{
				if ((this._Section_Grade != value))
				{
					this._Section_Grade = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section_name", DbType="VarChar(30)")]
		public string Section_name
		{
			get
			{
				return this._Section_name;
			}
			set
			{
				if ((this._Section_name != value))
				{
					this._Section_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Question", DbType="NVarChar(80)")]
		public string Question
		{
			get
			{
				return this._Question;
			}
			set
			{
				if ((this._Question != value))
				{
					this._Question = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Answer", DbType="NVarChar(80)")]
		public string Answer
		{
			get
			{
				return this._Answer;
			}
			set
			{
				if ((this._Answer != value))
				{
					this._Answer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Choice1", DbType="NVarChar(80)")]
		public string Choice1
		{
			get
			{
				return this._Choice1;
			}
			set
			{
				if ((this._Choice1 != value))
				{
					this._Choice1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Choice2", DbType="NVarChar(80)")]
		public string Choice2
		{
			get
			{
				return this._Choice2;
			}
			set
			{
				if ((this._Choice2 != value))
				{
					this._Choice2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Choice3", DbType="NVarChar(80)")]
		public string Choice3
		{
			get
			{
				return this._Choice3;
			}
			set
			{
				if ((this._Choice3 != value))
				{
					this._Choice3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_ID", DbType="VarChar(30)")]
		public string T_ID
		{
			get
			{
				return this._T_ID;
			}
			set
			{
				if ((this._T_ID != value))
				{
					this._T_ID = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblTeacher")]
	public partial class tblTeacher : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _T_ID;
		
		private string _T_Username;
		
		private string _T_Password;
		
		private string _T_LastName;
		
		private string _T_FirstName;
		
		private string _T_UserType;
		
		private EntitySet<tblSection> _tblSections;
		
		private EntitySet<tblStudent> _tblStudents;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnT_IDChanging(string value);
    partial void OnT_IDChanged();
    partial void OnT_UsernameChanging(string value);
    partial void OnT_UsernameChanged();
    partial void OnT_PasswordChanging(string value);
    partial void OnT_PasswordChanged();
    partial void OnT_LastNameChanging(string value);
    partial void OnT_LastNameChanged();
    partial void OnT_FirstNameChanging(string value);
    partial void OnT_FirstNameChanged();
    partial void OnT_UserTypeChanging(string value);
    partial void OnT_UserTypeChanged();
    #endregion
		
		public tblTeacher()
		{
			this._tblSections = new EntitySet<tblSection>(new Action<tblSection>(this.attach_tblSections), new Action<tblSection>(this.detach_tblSections));
			this._tblStudents = new EntitySet<tblStudent>(new Action<tblStudent>(this.attach_tblStudents), new Action<tblStudent>(this.detach_tblStudents));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_ID", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string T_ID
		{
			get
			{
				return this._T_ID;
			}
			set
			{
				if ((this._T_ID != value))
				{
					this.OnT_IDChanging(value);
					this.SendPropertyChanging();
					this._T_ID = value;
					this.SendPropertyChanged("T_ID");
					this.OnT_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_Username", DbType="VarChar(30)")]
		public string T_Username
		{
			get
			{
				return this._T_Username;
			}
			set
			{
				if ((this._T_Username != value))
				{
					this.OnT_UsernameChanging(value);
					this.SendPropertyChanging();
					this._T_Username = value;
					this.SendPropertyChanged("T_Username");
					this.OnT_UsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_Password", DbType="VarChar(30)")]
		public string T_Password
		{
			get
			{
				return this._T_Password;
			}
			set
			{
				if ((this._T_Password != value))
				{
					this.OnT_PasswordChanging(value);
					this.SendPropertyChanging();
					this._T_Password = value;
					this.SendPropertyChanged("T_Password");
					this.OnT_PasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_LastName", DbType="NVarChar(30)")]
		public string T_LastName
		{
			get
			{
				return this._T_LastName;
			}
			set
			{
				if ((this._T_LastName != value))
				{
					this.OnT_LastNameChanging(value);
					this.SendPropertyChanging();
					this._T_LastName = value;
					this.SendPropertyChanged("T_LastName");
					this.OnT_LastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_FirstName", DbType="NVarChar(30)")]
		public string T_FirstName
		{
			get
			{
				return this._T_FirstName;
			}
			set
			{
				if ((this._T_FirstName != value))
				{
					this.OnT_FirstNameChanging(value);
					this.SendPropertyChanging();
					this._T_FirstName = value;
					this.SendPropertyChanged("T_FirstName");
					this.OnT_FirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_UserType", DbType="VarChar(30)")]
		public string T_UserType
		{
			get
			{
				return this._T_UserType;
			}
			set
			{
				if ((this._T_UserType != value))
				{
					this.OnT_UserTypeChanging(value);
					this.SendPropertyChanging();
					this._T_UserType = value;
					this.SendPropertyChanged("T_UserType");
					this.OnT_UserTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblTeacher_tblSection", Storage="_tblSections", ThisKey="T_ID", OtherKey="T_ID")]
		public EntitySet<tblSection> tblSections
		{
			get
			{
				return this._tblSections;
			}
			set
			{
				this._tblSections.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblTeacher_tblStudent", Storage="_tblStudents", ThisKey="T_ID", OtherKey="T_ID")]
		public EntitySet<tblStudent> tblStudents
		{
			get
			{
				return this._tblStudents;
			}
			set
			{
				this._tblStudents.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblSections(tblSection entity)
		{
			this.SendPropertyChanging();
			entity.tblTeacher = this;
		}
		
		private void detach_tblSections(tblSection entity)
		{
			this.SendPropertyChanging();
			entity.tblTeacher = null;
		}
		
		private void attach_tblStudents(tblStudent entity)
		{
			this.SendPropertyChanging();
			entity.tblTeacher = this;
		}
		
		private void detach_tblStudents(tblStudent entity)
		{
			this.SendPropertyChanging();
			entity.tblTeacher = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblScore")]
	public partial class tblScore
	{
		
		private string _S_ID;
		
		private string _T_ID;
		
		private string _S_LastName;
		
		private string _S_FirstName;
		
		private string _Section_Grade;
		
		private string _Section_name;
		
		private string _Correct;
		
		private string _Wrong;
		
		public tblScore()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_ID", DbType="VarChar(30)")]
		public string S_ID
		{
			get
			{
				return this._S_ID;
			}
			set
			{
				if ((this._S_ID != value))
				{
					this._S_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_ID", DbType="VarChar(30)")]
		public string T_ID
		{
			get
			{
				return this._T_ID;
			}
			set
			{
				if ((this._T_ID != value))
				{
					this._T_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_LastName", DbType="NVarChar(30)")]
		public string S_LastName
		{
			get
			{
				return this._S_LastName;
			}
			set
			{
				if ((this._S_LastName != value))
				{
					this._S_LastName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_FirstName", DbType="NVarChar(30)")]
		public string S_FirstName
		{
			get
			{
				return this._S_FirstName;
			}
			set
			{
				if ((this._S_FirstName != value))
				{
					this._S_FirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section_Grade", DbType="VarChar(30)")]
		public string Section_Grade
		{
			get
			{
				return this._Section_Grade;
			}
			set
			{
				if ((this._Section_Grade != value))
				{
					this._Section_Grade = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section_name", DbType="VarChar(30)")]
		public string Section_name
		{
			get
			{
				return this._Section_name;
			}
			set
			{
				if ((this._Section_name != value))
				{
					this._Section_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correct", DbType="VarChar(30)")]
		public string Correct
		{
			get
			{
				return this._Correct;
			}
			set
			{
				if ((this._Correct != value))
				{
					this._Correct = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wrong", DbType="VarChar(30)")]
		public string Wrong
		{
			get
			{
				return this._Wrong;
			}
			set
			{
				if ((this._Wrong != value))
				{
					this._Wrong = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblSection")]
	public partial class tblSection : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Section_ID;
		
		private string _Section_name;
		
		private string _Section_Grade;
		
		private string _T_ID;
		
		private string _T_Name;
		
		private EntityRef<tblTeacher> _tblTeacher;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSection_IDChanging(string value);
    partial void OnSection_IDChanged();
    partial void OnSection_nameChanging(string value);
    partial void OnSection_nameChanged();
    partial void OnSection_GradeChanging(string value);
    partial void OnSection_GradeChanged();
    partial void OnT_IDChanging(string value);
    partial void OnT_IDChanged();
    partial void OnT_NameChanging(string value);
    partial void OnT_NameChanged();
    #endregion
		
		public tblSection()
		{
			this._tblTeacher = default(EntityRef<tblTeacher>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section_ID", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Section_ID
		{
			get
			{
				return this._Section_ID;
			}
			set
			{
				if ((this._Section_ID != value))
				{
					this.OnSection_IDChanging(value);
					this.SendPropertyChanging();
					this._Section_ID = value;
					this.SendPropertyChanged("Section_ID");
					this.OnSection_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section_name", DbType="VarChar(30)")]
		public string Section_name
		{
			get
			{
				return this._Section_name;
			}
			set
			{
				if ((this._Section_name != value))
				{
					this.OnSection_nameChanging(value);
					this.SendPropertyChanging();
					this._Section_name = value;
					this.SendPropertyChanged("Section_name");
					this.OnSection_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section_Grade", DbType="VarChar(30)")]
		public string Section_Grade
		{
			get
			{
				return this._Section_Grade;
			}
			set
			{
				if ((this._Section_Grade != value))
				{
					this.OnSection_GradeChanging(value);
					this.SendPropertyChanging();
					this._Section_Grade = value;
					this.SendPropertyChanged("Section_Grade");
					this.OnSection_GradeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_ID", DbType="VarChar(30)")]
		public string T_ID
		{
			get
			{
				return this._T_ID;
			}
			set
			{
				if ((this._T_ID != value))
				{
					if (this._tblTeacher.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnT_IDChanging(value);
					this.SendPropertyChanging();
					this._T_ID = value;
					this.SendPropertyChanged("T_ID");
					this.OnT_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_Name", DbType="VarChar(30)")]
		public string T_Name
		{
			get
			{
				return this._T_Name;
			}
			set
			{
				if ((this._T_Name != value))
				{
					this.OnT_NameChanging(value);
					this.SendPropertyChanging();
					this._T_Name = value;
					this.SendPropertyChanged("T_Name");
					this.OnT_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblTeacher_tblSection", Storage="_tblTeacher", ThisKey="T_ID", OtherKey="T_ID", IsForeignKey=true)]
		public tblTeacher tblTeacher
		{
			get
			{
				return this._tblTeacher.Entity;
			}
			set
			{
				tblTeacher previousValue = this._tblTeacher.Entity;
				if (((previousValue != value) 
							|| (this._tblTeacher.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblTeacher.Entity = null;
						previousValue.tblSections.Remove(this);
					}
					this._tblTeacher.Entity = value;
					if ((value != null))
					{
						value.tblSections.Add(this);
						this._T_ID = value.T_ID;
					}
					else
					{
						this._T_ID = default(string);
					}
					this.SendPropertyChanged("tblTeacher");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblStudent")]
	public partial class tblStudent : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _S_ID;
		
		private string _S_Username;
		
		private string _S_Password;
		
		private string _S_LastName;
		
		private string _S_FirstName;
		
		private string _Section_Grade;
		
		private string _Section_name;
		
		private string _T_ID;
		
		private string _T_name;
		
		private EntityRef<tblTeacher> _tblTeacher;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnS_IDChanging(string value);
    partial void OnS_IDChanged();
    partial void OnS_UsernameChanging(string value);
    partial void OnS_UsernameChanged();
    partial void OnS_PasswordChanging(string value);
    partial void OnS_PasswordChanged();
    partial void OnS_LastNameChanging(string value);
    partial void OnS_LastNameChanged();
    partial void OnS_FirstNameChanging(string value);
    partial void OnS_FirstNameChanged();
    partial void OnSection_GradeChanging(string value);
    partial void OnSection_GradeChanged();
    partial void OnSection_nameChanging(string value);
    partial void OnSection_nameChanged();
    partial void OnT_IDChanging(string value);
    partial void OnT_IDChanged();
    partial void OnT_nameChanging(string value);
    partial void OnT_nameChanged();
    #endregion
		
		public tblStudent()
		{
			this._tblTeacher = default(EntityRef<tblTeacher>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_ID", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string S_ID
		{
			get
			{
				return this._S_ID;
			}
			set
			{
				if ((this._S_ID != value))
				{
					this.OnS_IDChanging(value);
					this.SendPropertyChanging();
					this._S_ID = value;
					this.SendPropertyChanged("S_ID");
					this.OnS_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_Username", DbType="VarChar(30)")]
		public string S_Username
		{
			get
			{
				return this._S_Username;
			}
			set
			{
				if ((this._S_Username != value))
				{
					this.OnS_UsernameChanging(value);
					this.SendPropertyChanging();
					this._S_Username = value;
					this.SendPropertyChanged("S_Username");
					this.OnS_UsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_Password", DbType="VarChar(30)")]
		public string S_Password
		{
			get
			{
				return this._S_Password;
			}
			set
			{
				if ((this._S_Password != value))
				{
					this.OnS_PasswordChanging(value);
					this.SendPropertyChanging();
					this._S_Password = value;
					this.SendPropertyChanged("S_Password");
					this.OnS_PasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_LastName", DbType="NVarChar(30)")]
		public string S_LastName
		{
			get
			{
				return this._S_LastName;
			}
			set
			{
				if ((this._S_LastName != value))
				{
					this.OnS_LastNameChanging(value);
					this.SendPropertyChanging();
					this._S_LastName = value;
					this.SendPropertyChanged("S_LastName");
					this.OnS_LastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_FirstName", DbType="NVarChar(30)")]
		public string S_FirstName
		{
			get
			{
				return this._S_FirstName;
			}
			set
			{
				if ((this._S_FirstName != value))
				{
					this.OnS_FirstNameChanging(value);
					this.SendPropertyChanging();
					this._S_FirstName = value;
					this.SendPropertyChanged("S_FirstName");
					this.OnS_FirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section_Grade", DbType="VarChar(30)")]
		public string Section_Grade
		{
			get
			{
				return this._Section_Grade;
			}
			set
			{
				if ((this._Section_Grade != value))
				{
					this.OnSection_GradeChanging(value);
					this.SendPropertyChanging();
					this._Section_Grade = value;
					this.SendPropertyChanged("Section_Grade");
					this.OnSection_GradeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section_name", DbType="VarChar(30)")]
		public string Section_name
		{
			get
			{
				return this._Section_name;
			}
			set
			{
				if ((this._Section_name != value))
				{
					this.OnSection_nameChanging(value);
					this.SendPropertyChanging();
					this._Section_name = value;
					this.SendPropertyChanged("Section_name");
					this.OnSection_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_ID", DbType="VarChar(30)")]
		public string T_ID
		{
			get
			{
				return this._T_ID;
			}
			set
			{
				if ((this._T_ID != value))
				{
					if (this._tblTeacher.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnT_IDChanging(value);
					this.SendPropertyChanging();
					this._T_ID = value;
					this.SendPropertyChanged("T_ID");
					this.OnT_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_name", DbType="VarChar(30)")]
		public string T_name
		{
			get
			{
				return this._T_name;
			}
			set
			{
				if ((this._T_name != value))
				{
					this.OnT_nameChanging(value);
					this.SendPropertyChanging();
					this._T_name = value;
					this.SendPropertyChanged("T_name");
					this.OnT_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblTeacher_tblStudent", Storage="_tblTeacher", ThisKey="T_ID", OtherKey="T_ID", IsForeignKey=true)]
		public tblTeacher tblTeacher
		{
			get
			{
				return this._tblTeacher.Entity;
			}
			set
			{
				tblTeacher previousValue = this._tblTeacher.Entity;
				if (((previousValue != value) 
							|| (this._tblTeacher.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblTeacher.Entity = null;
						previousValue.tblStudents.Remove(this);
					}
					this._tblTeacher.Entity = value;
					if ((value != null))
					{
						value.tblStudents.Add(this);
						this._T_ID = value.T_ID;
					}
					else
					{
						this._T_ID = default(string);
					}
					this.SendPropertyChanged("tblTeacher");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class sp_viewTeacherResult
	{
		
		private string _LastName;
		
		private string _FirstName;
		
		public sp_viewTeacherResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(30)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this._LastName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(30)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this._FirstName = value;
				}
			}
		}
	}
	
	public partial class sp_countQuezResult
	{
		
		private System.Nullable<int> _countQ;
		
		public sp_countQuezResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_countQ", DbType="Int")]
		public System.Nullable<int> countQ
		{
			get
			{
				return this._countQ;
			}
			set
			{
				if ((this._countQ != value))
				{
					this._countQ = value;
				}
			}
		}
	}
	
	public partial class sp_NameTeacherResult
	{
		
		private string _T_ID;
		
		private string _T_Username;
		
		private string _T_Password;
		
		private string _T_LastName;
		
		private string _T_FirstName;
		
		private string _T_UserType;
		
		public sp_NameTeacherResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_ID", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string T_ID
		{
			get
			{
				return this._T_ID;
			}
			set
			{
				if ((this._T_ID != value))
				{
					this._T_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_Username", DbType="VarChar(30)")]
		public string T_Username
		{
			get
			{
				return this._T_Username;
			}
			set
			{
				if ((this._T_Username != value))
				{
					this._T_Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_Password", DbType="VarChar(30)")]
		public string T_Password
		{
			get
			{
				return this._T_Password;
			}
			set
			{
				if ((this._T_Password != value))
				{
					this._T_Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_LastName", DbType="NVarChar(30)")]
		public string T_LastName
		{
			get
			{
				return this._T_LastName;
			}
			set
			{
				if ((this._T_LastName != value))
				{
					this._T_LastName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_FirstName", DbType="NVarChar(30)")]
		public string T_FirstName
		{
			get
			{
				return this._T_FirstName;
			}
			set
			{
				if ((this._T_FirstName != value))
				{
					this._T_FirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_UserType", DbType="VarChar(30)")]
		public string T_UserType
		{
			get
			{
				return this._T_UserType;
			}
			set
			{
				if ((this._T_UserType != value))
				{
					this._T_UserType = value;
				}
			}
		}
	}
	
	public partial class sp_retrieveIDResult
	{
		
		private string _T_ID;
		
		private string _T_Username;
		
		private string _T_Password;
		
		private string _T_LastName;
		
		private string _T_FirstName;
		
		private string _T_UserType;
		
		public sp_retrieveIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_ID", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string T_ID
		{
			get
			{
				return this._T_ID;
			}
			set
			{
				if ((this._T_ID != value))
				{
					this._T_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_Username", DbType="VarChar(30)")]
		public string T_Username
		{
			get
			{
				return this._T_Username;
			}
			set
			{
				if ((this._T_Username != value))
				{
					this._T_Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_Password", DbType="VarChar(30)")]
		public string T_Password
		{
			get
			{
				return this._T_Password;
			}
			set
			{
				if ((this._T_Password != value))
				{
					this._T_Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_LastName", DbType="NVarChar(30)")]
		public string T_LastName
		{
			get
			{
				return this._T_LastName;
			}
			set
			{
				if ((this._T_LastName != value))
				{
					this._T_LastName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_FirstName", DbType="NVarChar(30)")]
		public string T_FirstName
		{
			get
			{
				return this._T_FirstName;
			}
			set
			{
				if ((this._T_FirstName != value))
				{
					this._T_FirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_UserType", DbType="VarChar(30)")]
		public string T_UserType
		{
			get
			{
				return this._T_UserType;
			}
			set
			{
				if ((this._T_UserType != value))
				{
					this._T_UserType = value;
				}
			}
		}
	}
	
	public partial class sp_retrieveIDStudentResult
	{
		
		private string _S_ID;
		
		private string _S_Username;
		
		private string _S_Password;
		
		private string _S_LastName;
		
		private string _S_FirstName;
		
		private string _Section_Grade;
		
		private string _Section_name;
		
		private string _T_ID;
		
		private string _T_name;
		
		public sp_retrieveIDStudentResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_ID", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string S_ID
		{
			get
			{
				return this._S_ID;
			}
			set
			{
				if ((this._S_ID != value))
				{
					this._S_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_Username", DbType="VarChar(30)")]
		public string S_Username
		{
			get
			{
				return this._S_Username;
			}
			set
			{
				if ((this._S_Username != value))
				{
					this._S_Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_Password", DbType="VarChar(30)")]
		public string S_Password
		{
			get
			{
				return this._S_Password;
			}
			set
			{
				if ((this._S_Password != value))
				{
					this._S_Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_LastName", DbType="NVarChar(30)")]
		public string S_LastName
		{
			get
			{
				return this._S_LastName;
			}
			set
			{
				if ((this._S_LastName != value))
				{
					this._S_LastName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_FirstName", DbType="NVarChar(30)")]
		public string S_FirstName
		{
			get
			{
				return this._S_FirstName;
			}
			set
			{
				if ((this._S_FirstName != value))
				{
					this._S_FirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section_Grade", DbType="VarChar(30)")]
		public string Section_Grade
		{
			get
			{
				return this._Section_Grade;
			}
			set
			{
				if ((this._Section_Grade != value))
				{
					this._Section_Grade = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section_name", DbType="VarChar(30)")]
		public string Section_name
		{
			get
			{
				return this._Section_name;
			}
			set
			{
				if ((this._Section_name != value))
				{
					this._Section_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_ID", DbType="VarChar(30)")]
		public string T_ID
		{
			get
			{
				return this._T_ID;
			}
			set
			{
				if ((this._T_ID != value))
				{
					this._T_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_name", DbType="VarChar(30)")]
		public string T_name
		{
			get
			{
				return this._T_name;
			}
			set
			{
				if ((this._T_name != value))
				{
					this._T_name = value;
				}
			}
		}
	}
	
	public partial class sp_retrieveInfoStudentResult
	{
		
		private string _S_ID;
		
		private string _S_Username;
		
		private string _S_Password;
		
		private string _S_LastName;
		
		private string _S_FirstName;
		
		private string _Section_Grade;
		
		private string _Section_name;
		
		private string _T_ID;
		
		private string _T_name;
		
		public sp_retrieveInfoStudentResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_ID", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string S_ID
		{
			get
			{
				return this._S_ID;
			}
			set
			{
				if ((this._S_ID != value))
				{
					this._S_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_Username", DbType="VarChar(30)")]
		public string S_Username
		{
			get
			{
				return this._S_Username;
			}
			set
			{
				if ((this._S_Username != value))
				{
					this._S_Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_Password", DbType="VarChar(30)")]
		public string S_Password
		{
			get
			{
				return this._S_Password;
			}
			set
			{
				if ((this._S_Password != value))
				{
					this._S_Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_LastName", DbType="NVarChar(30)")]
		public string S_LastName
		{
			get
			{
				return this._S_LastName;
			}
			set
			{
				if ((this._S_LastName != value))
				{
					this._S_LastName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_FirstName", DbType="NVarChar(30)")]
		public string S_FirstName
		{
			get
			{
				return this._S_FirstName;
			}
			set
			{
				if ((this._S_FirstName != value))
				{
					this._S_FirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section_Grade", DbType="VarChar(30)")]
		public string Section_Grade
		{
			get
			{
				return this._Section_Grade;
			}
			set
			{
				if ((this._Section_Grade != value))
				{
					this._Section_Grade = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section_name", DbType="VarChar(30)")]
		public string Section_name
		{
			get
			{
				return this._Section_name;
			}
			set
			{
				if ((this._Section_name != value))
				{
					this._Section_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_ID", DbType="VarChar(30)")]
		public string T_ID
		{
			get
			{
				return this._T_ID;
			}
			set
			{
				if ((this._T_ID != value))
				{
					this._T_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_name", DbType="VarChar(30)")]
		public string T_name
		{
			get
			{
				return this._T_name;
			}
			set
			{
				if ((this._T_name != value))
				{
					this._T_name = value;
				}
			}
		}
	}
	
	public partial class sp_retrieveNameResult
	{
		
		private string _T_ID;
		
		private string _T_Username;
		
		private string _T_Password;
		
		private string _T_LastName;
		
		private string _T_FirstName;
		
		private string _T_UserType;
		
		public sp_retrieveNameResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_ID", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string T_ID
		{
			get
			{
				return this._T_ID;
			}
			set
			{
				if ((this._T_ID != value))
				{
					this._T_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_Username", DbType="VarChar(30)")]
		public string T_Username
		{
			get
			{
				return this._T_Username;
			}
			set
			{
				if ((this._T_Username != value))
				{
					this._T_Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_Password", DbType="VarChar(30)")]
		public string T_Password
		{
			get
			{
				return this._T_Password;
			}
			set
			{
				if ((this._T_Password != value))
				{
					this._T_Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_LastName", DbType="NVarChar(30)")]
		public string T_LastName
		{
			get
			{
				return this._T_LastName;
			}
			set
			{
				if ((this._T_LastName != value))
				{
					this._T_LastName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_FirstName", DbType="NVarChar(30)")]
		public string T_FirstName
		{
			get
			{
				return this._T_FirstName;
			}
			set
			{
				if ((this._T_FirstName != value))
				{
					this._T_FirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_UserType", DbType="VarChar(30)")]
		public string T_UserType
		{
			get
			{
				return this._T_UserType;
			}
			set
			{
				if ((this._T_UserType != value))
				{
					this._T_UserType = value;
				}
			}
		}
	}
	
	public partial class sp_RetrieveQuizResult
	{
		
		private System.Nullable<int> _No;
		
		private string _Section_Grade;
		
		private string _Section_name;
		
		private string _Question;
		
		private string _Answer;
		
		private string _Choice1;
		
		private string _Choice2;
		
		private string _Choice3;
		
		private string _T_ID;
		
		public sp_RetrieveQuizResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_No", DbType="Int")]
		public System.Nullable<int> No
		{
			get
			{
				return this._No;
			}
			set
			{
				if ((this._No != value))
				{
					this._No = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section_Grade", DbType="VarChar(30)")]
		public string Section_Grade
		{
			get
			{
				return this._Section_Grade;
			}
			set
			{
				if ((this._Section_Grade != value))
				{
					this._Section_Grade = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section_name", DbType="VarChar(30)")]
		public string Section_name
		{
			get
			{
				return this._Section_name;
			}
			set
			{
				if ((this._Section_name != value))
				{
					this._Section_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Question", DbType="NVarChar(80)")]
		public string Question
		{
			get
			{
				return this._Question;
			}
			set
			{
				if ((this._Question != value))
				{
					this._Question = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Answer", DbType="NVarChar(80)")]
		public string Answer
		{
			get
			{
				return this._Answer;
			}
			set
			{
				if ((this._Answer != value))
				{
					this._Answer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Choice1", DbType="NVarChar(80)")]
		public string Choice1
		{
			get
			{
				return this._Choice1;
			}
			set
			{
				if ((this._Choice1 != value))
				{
					this._Choice1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Choice2", DbType="NVarChar(80)")]
		public string Choice2
		{
			get
			{
				return this._Choice2;
			}
			set
			{
				if ((this._Choice2 != value))
				{
					this._Choice2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Choice3", DbType="NVarChar(80)")]
		public string Choice3
		{
			get
			{
				return this._Choice3;
			}
			set
			{
				if ((this._Choice3 != value))
				{
					this._Choice3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_ID", DbType="VarChar(30)")]
		public string T_ID
		{
			get
			{
				return this._T_ID;
			}
			set
			{
				if ((this._T_ID != value))
				{
					this._T_ID = value;
				}
			}
		}
	}
	
	public partial class sp_retrieveScoreResult
	{
		
		private string _S_ID;
		
		private string _T_ID;
		
		private string _S_LastName;
		
		private string _S_FirstName;
		
		private string _Section_Grade;
		
		private string _Section_name;
		
		private string _Correct;
		
		private string _Wrong;
		
		public sp_retrieveScoreResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_ID", DbType="VarChar(30)")]
		public string S_ID
		{
			get
			{
				return this._S_ID;
			}
			set
			{
				if ((this._S_ID != value))
				{
					this._S_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_ID", DbType="VarChar(30)")]
		public string T_ID
		{
			get
			{
				return this._T_ID;
			}
			set
			{
				if ((this._T_ID != value))
				{
					this._T_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_LastName", DbType="NVarChar(30)")]
		public string S_LastName
		{
			get
			{
				return this._S_LastName;
			}
			set
			{
				if ((this._S_LastName != value))
				{
					this._S_LastName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_FirstName", DbType="NVarChar(30)")]
		public string S_FirstName
		{
			get
			{
				return this._S_FirstName;
			}
			set
			{
				if ((this._S_FirstName != value))
				{
					this._S_FirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section_Grade", DbType="VarChar(30)")]
		public string Section_Grade
		{
			get
			{
				return this._Section_Grade;
			}
			set
			{
				if ((this._Section_Grade != value))
				{
					this._Section_Grade = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section_name", DbType="VarChar(30)")]
		public string Section_name
		{
			get
			{
				return this._Section_name;
			}
			set
			{
				if ((this._Section_name != value))
				{
					this._Section_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correct", DbType="VarChar(30)")]
		public string Correct
		{
			get
			{
				return this._Correct;
			}
			set
			{
				if ((this._Correct != value))
				{
					this._Correct = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wrong", DbType="VarChar(30)")]
		public string Wrong
		{
			get
			{
				return this._Wrong;
			}
			set
			{
				if ((this._Wrong != value))
				{
					this._Wrong = value;
				}
			}
		}
	}
	
	public partial class sp_retrieveSectionResult
	{
		
		private string _Section_ID;
		
		private string _Section_name;
		
		private string _Section_Grade;
		
		private string _T_ID;
		
		private string _T_Name;
		
		public sp_retrieveSectionResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section_ID", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Section_ID
		{
			get
			{
				return this._Section_ID;
			}
			set
			{
				if ((this._Section_ID != value))
				{
					this._Section_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section_name", DbType="VarChar(30)")]
		public string Section_name
		{
			get
			{
				return this._Section_name;
			}
			set
			{
				if ((this._Section_name != value))
				{
					this._Section_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section_Grade", DbType="VarChar(30)")]
		public string Section_Grade
		{
			get
			{
				return this._Section_Grade;
			}
			set
			{
				if ((this._Section_Grade != value))
				{
					this._Section_Grade = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_ID", DbType="VarChar(30)")]
		public string T_ID
		{
			get
			{
				return this._T_ID;
			}
			set
			{
				if ((this._T_ID != value))
				{
					this._T_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_Name", DbType="VarChar(30)")]
		public string T_Name
		{
			get
			{
				return this._T_Name;
			}
			set
			{
				if ((this._T_Name != value))
				{
					this._T_Name = value;
				}
			}
		}
	}
	
	public partial class sp_retrieveStudentResult
	{
		
		private string _S_ID;
		
		private string _S_Username;
		
		private string _S_Password;
		
		private string _S_LastName;
		
		private string _S_FirstName;
		
		private string _Section_Grade;
		
		private string _Section_name;
		
		private string _T_ID;
		
		private string _T_name;
		
		public sp_retrieveStudentResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_ID", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string S_ID
		{
			get
			{
				return this._S_ID;
			}
			set
			{
				if ((this._S_ID != value))
				{
					this._S_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_Username", DbType="VarChar(30)")]
		public string S_Username
		{
			get
			{
				return this._S_Username;
			}
			set
			{
				if ((this._S_Username != value))
				{
					this._S_Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_Password", DbType="VarChar(30)")]
		public string S_Password
		{
			get
			{
				return this._S_Password;
			}
			set
			{
				if ((this._S_Password != value))
				{
					this._S_Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_LastName", DbType="NVarChar(30)")]
		public string S_LastName
		{
			get
			{
				return this._S_LastName;
			}
			set
			{
				if ((this._S_LastName != value))
				{
					this._S_LastName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_FirstName", DbType="NVarChar(30)")]
		public string S_FirstName
		{
			get
			{
				return this._S_FirstName;
			}
			set
			{
				if ((this._S_FirstName != value))
				{
					this._S_FirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section_Grade", DbType="VarChar(30)")]
		public string Section_Grade
		{
			get
			{
				return this._Section_Grade;
			}
			set
			{
				if ((this._Section_Grade != value))
				{
					this._Section_Grade = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section_name", DbType="VarChar(30)")]
		public string Section_name
		{
			get
			{
				return this._Section_name;
			}
			set
			{
				if ((this._Section_name != value))
				{
					this._Section_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_ID", DbType="VarChar(30)")]
		public string T_ID
		{
			get
			{
				return this._T_ID;
			}
			set
			{
				if ((this._T_ID != value))
				{
					this._T_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_name", DbType="VarChar(30)")]
		public string T_name
		{
			get
			{
				return this._T_name;
			}
			set
			{
				if ((this._T_name != value))
				{
					this._T_name = value;
				}
			}
		}
	}
	
	public partial class sp_retrieveTeacherResult
	{
		
		private string _T_ID;
		
		private string _T_Username;
		
		private string _T_Password;
		
		private string _T_LastName;
		
		private string _T_FirstName;
		
		private string _T_UserType;
		
		public sp_retrieveTeacherResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_ID", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string T_ID
		{
			get
			{
				return this._T_ID;
			}
			set
			{
				if ((this._T_ID != value))
				{
					this._T_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_Username", DbType="VarChar(30)")]
		public string T_Username
		{
			get
			{
				return this._T_Username;
			}
			set
			{
				if ((this._T_Username != value))
				{
					this._T_Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_Password", DbType="VarChar(30)")]
		public string T_Password
		{
			get
			{
				return this._T_Password;
			}
			set
			{
				if ((this._T_Password != value))
				{
					this._T_Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_LastName", DbType="NVarChar(30)")]
		public string T_LastName
		{
			get
			{
				return this._T_LastName;
			}
			set
			{
				if ((this._T_LastName != value))
				{
					this._T_LastName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_FirstName", DbType="NVarChar(30)")]
		public string T_FirstName
		{
			get
			{
				return this._T_FirstName;
			}
			set
			{
				if ((this._T_FirstName != value))
				{
					this._T_FirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_UserType", DbType="VarChar(30)")]
		public string T_UserType
		{
			get
			{
				return this._T_UserType;
			}
			set
			{
				if ((this._T_UserType != value))
				{
					this._T_UserType = value;
				}
			}
		}
	}
	
	public partial class sp_retrieveUsernameStudentResult
	{
		
		private string _S_ID;
		
		private string _S_Username;
		
		private string _S_Password;
		
		private string _S_LastName;
		
		private string _S_FirstName;
		
		private string _Section_Grade;
		
		private string _Section_name;
		
		private string _T_ID;
		
		private string _T_name;
		
		public sp_retrieveUsernameStudentResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_ID", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string S_ID
		{
			get
			{
				return this._S_ID;
			}
			set
			{
				if ((this._S_ID != value))
				{
					this._S_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_Username", DbType="VarChar(30)")]
		public string S_Username
		{
			get
			{
				return this._S_Username;
			}
			set
			{
				if ((this._S_Username != value))
				{
					this._S_Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_Password", DbType="VarChar(30)")]
		public string S_Password
		{
			get
			{
				return this._S_Password;
			}
			set
			{
				if ((this._S_Password != value))
				{
					this._S_Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_LastName", DbType="NVarChar(30)")]
		public string S_LastName
		{
			get
			{
				return this._S_LastName;
			}
			set
			{
				if ((this._S_LastName != value))
				{
					this._S_LastName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_FirstName", DbType="NVarChar(30)")]
		public string S_FirstName
		{
			get
			{
				return this._S_FirstName;
			}
			set
			{
				if ((this._S_FirstName != value))
				{
					this._S_FirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section_Grade", DbType="VarChar(30)")]
		public string Section_Grade
		{
			get
			{
				return this._Section_Grade;
			}
			set
			{
				if ((this._Section_Grade != value))
				{
					this._Section_Grade = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section_name", DbType="VarChar(30)")]
		public string Section_name
		{
			get
			{
				return this._Section_name;
			}
			set
			{
				if ((this._Section_name != value))
				{
					this._Section_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_ID", DbType="VarChar(30)")]
		public string T_ID
		{
			get
			{
				return this._T_ID;
			}
			set
			{
				if ((this._T_ID != value))
				{
					this._T_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_name", DbType="VarChar(30)")]
		public string T_name
		{
			get
			{
				return this._T_name;
			}
			set
			{
				if ((this._T_name != value))
				{
					this._T_name = value;
				}
			}
		}
	}
	
	public partial class sp_retrieveUsernameTeacherResult
	{
		
		private string _T_ID;
		
		private string _T_Username;
		
		private string _T_Password;
		
		private string _T_LastName;
		
		private string _T_FirstName;
		
		private string _T_UserType;
		
		public sp_retrieveUsernameTeacherResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_ID", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string T_ID
		{
			get
			{
				return this._T_ID;
			}
			set
			{
				if ((this._T_ID != value))
				{
					this._T_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_Username", DbType="VarChar(30)")]
		public string T_Username
		{
			get
			{
				return this._T_Username;
			}
			set
			{
				if ((this._T_Username != value))
				{
					this._T_Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_Password", DbType="VarChar(30)")]
		public string T_Password
		{
			get
			{
				return this._T_Password;
			}
			set
			{
				if ((this._T_Password != value))
				{
					this._T_Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_LastName", DbType="NVarChar(30)")]
		public string T_LastName
		{
			get
			{
				return this._T_LastName;
			}
			set
			{
				if ((this._T_LastName != value))
				{
					this._T_LastName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_FirstName", DbType="NVarChar(30)")]
		public string T_FirstName
		{
			get
			{
				return this._T_FirstName;
			}
			set
			{
				if ((this._T_FirstName != value))
				{
					this._T_FirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_UserType", DbType="VarChar(30)")]
		public string T_UserType
		{
			get
			{
				return this._T_UserType;
			}
			set
			{
				if ((this._T_UserType != value))
				{
					this._T_UserType = value;
				}
			}
		}
	}
	
	public partial class sp_searchQuestionResult
	{
		
		private System.Nullable<int> _No;
		
		private string _Question;
		
		public sp_searchQuestionResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_No", DbType="Int")]
		public System.Nullable<int> No
		{
			get
			{
				return this._No;
			}
			set
			{
				if ((this._No != value))
				{
					this._No = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Question", DbType="NVarChar(80)")]
		public string Question
		{
			get
			{
				return this._Question;
			}
			set
			{
				if ((this._Question != value))
				{
					this._Question = value;
				}
			}
		}
	}
	
	public partial class sp_searchSResult
	{
		
		private string _Section;
		
		private string _Grade;
		
		private string _Teacher;
		
		public sp_searchSResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section", DbType="VarChar(30)")]
		public string Section
		{
			get
			{
				return this._Section;
			}
			set
			{
				if ((this._Section != value))
				{
					this._Section = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Grade", DbType="VarChar(30)")]
		public string Grade
		{
			get
			{
				return this._Grade;
			}
			set
			{
				if ((this._Grade != value))
				{
					this._Grade = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Teacher", DbType="VarChar(30)")]
		public string Teacher
		{
			get
			{
				return this._Teacher;
			}
			set
			{
				if ((this._Teacher != value))
				{
					this._Teacher = value;
				}
			}
		}
	}
	
	public partial class sp_searchStudentResult
	{
		
		private string _Lastname;
		
		private string _Firstname;
		
		private string _Section;
		
		private string _Grade;
		
		public sp_searchStudentResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lastname", DbType="NVarChar(30)")]
		public string Lastname
		{
			get
			{
				return this._Lastname;
			}
			set
			{
				if ((this._Lastname != value))
				{
					this._Lastname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Firstname", DbType="NVarChar(30)")]
		public string Firstname
		{
			get
			{
				return this._Firstname;
			}
			set
			{
				if ((this._Firstname != value))
				{
					this._Firstname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section", DbType="VarChar(30)")]
		public string Section
		{
			get
			{
				return this._Section;
			}
			set
			{
				if ((this._Section != value))
				{
					this._Section = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Grade", DbType="VarChar(30)")]
		public string Grade
		{
			get
			{
				return this._Grade;
			}
			set
			{
				if ((this._Grade != value))
				{
					this._Grade = value;
				}
			}
		}
	}
	
	public partial class sp_searchTResult
	{
		
		private string _Last_Name;
		
		private string _First_Name;
		
		public sp_searchTResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Last Name]", Storage="_Last_Name", DbType="NVarChar(30)")]
		public string Last_Name
		{
			get
			{
				return this._Last_Name;
			}
			set
			{
				if ((this._Last_Name != value))
				{
					this._Last_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[First Name]", Storage="_First_Name", DbType="NVarChar(30)")]
		public string First_Name
		{
			get
			{
				return this._First_Name;
			}
			set
			{
				if ((this._First_Name != value))
				{
					this._First_Name = value;
				}
			}
		}
	}
	
	public partial class sp_sectionIDResult
	{
		
		private System.Nullable<int> _CountS;
		
		public sp_sectionIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountS", DbType="Int")]
		public System.Nullable<int> CountS
		{
			get
			{
				return this._CountS;
			}
			set
			{
				if ((this._CountS != value))
				{
					this._CountS = value;
				}
			}
		}
	}
	
	public partial class sp_SelectScoreResult
	{
		
		private string _S_ID;
		
		private string _T_ID;
		
		private string _S_LastName;
		
		private string _S_FirstName;
		
		private string _Section_Grade;
		
		private string _Section_name;
		
		private string _Correct;
		
		private string _Wrong;
		
		public sp_SelectScoreResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_ID", DbType="VarChar(30)")]
		public string S_ID
		{
			get
			{
				return this._S_ID;
			}
			set
			{
				if ((this._S_ID != value))
				{
					this._S_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_ID", DbType="VarChar(30)")]
		public string T_ID
		{
			get
			{
				return this._T_ID;
			}
			set
			{
				if ((this._T_ID != value))
				{
					this._T_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_LastName", DbType="NVarChar(30)")]
		public string S_LastName
		{
			get
			{
				return this._S_LastName;
			}
			set
			{
				if ((this._S_LastName != value))
				{
					this._S_LastName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_FirstName", DbType="NVarChar(30)")]
		public string S_FirstName
		{
			get
			{
				return this._S_FirstName;
			}
			set
			{
				if ((this._S_FirstName != value))
				{
					this._S_FirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section_Grade", DbType="VarChar(30)")]
		public string Section_Grade
		{
			get
			{
				return this._Section_Grade;
			}
			set
			{
				if ((this._Section_Grade != value))
				{
					this._Section_Grade = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section_name", DbType="VarChar(30)")]
		public string Section_name
		{
			get
			{
				return this._Section_name;
			}
			set
			{
				if ((this._Section_name != value))
				{
					this._Section_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correct", DbType="VarChar(30)")]
		public string Correct
		{
			get
			{
				return this._Correct;
			}
			set
			{
				if ((this._Correct != value))
				{
					this._Correct = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wrong", DbType="VarChar(30)")]
		public string Wrong
		{
			get
			{
				return this._Wrong;
			}
			set
			{
				if ((this._Wrong != value))
				{
					this._Wrong = value;
				}
			}
		}
	}
	
	public partial class sp_selectSectionResult
	{
		
		private string _Section_Name;
		
		public sp_selectSectionResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section_Name", DbType="VarChar(30)")]
		public string Section_Name
		{
			get
			{
				return this._Section_Name;
			}
			set
			{
				if ((this._Section_Name != value))
				{
					this._Section_Name = value;
				}
			}
		}
	}
	
	public partial class sp_selectSectioninGradeResult
	{
		
		private string _Section_Name;
		
		private string _Section_Grade;
		
		public sp_selectSectioninGradeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section_Name", DbType="VarChar(30)")]
		public string Section_Name
		{
			get
			{
				return this._Section_Name;
			}
			set
			{
				if ((this._Section_Name != value))
				{
					this._Section_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section_Grade", DbType="VarChar(30)")]
		public string Section_Grade
		{
			get
			{
				return this._Section_Grade;
			}
			set
			{
				if ((this._Section_Grade != value))
				{
					this._Section_Grade = value;
				}
			}
		}
	}
	
	public partial class sp_SelectTeacherResult
	{
		
		private string _T_LastName;
		
		private string _T_FirstName;
		
		public sp_SelectTeacherResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_LastName", DbType="NVarChar(30)")]
		public string T_LastName
		{
			get
			{
				return this._T_LastName;
			}
			set
			{
				if ((this._T_LastName != value))
				{
					this._T_LastName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_FirstName", DbType="NVarChar(30)")]
		public string T_FirstName
		{
			get
			{
				return this._T_FirstName;
			}
			set
			{
				if ((this._T_FirstName != value))
				{
					this._T_FirstName = value;
				}
			}
		}
	}
	
	public partial class sp_StudentIDResult
	{
		
		private System.Nullable<int> _CountS;
		
		public sp_StudentIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountS", DbType="Int")]
		public System.Nullable<int> CountS
		{
			get
			{
				return this._CountS;
			}
			set
			{
				if ((this._CountS != value))
				{
					this._CountS = value;
				}
			}
		}
	}
	
	public partial class sp_teacherIDResult
	{
		
		private System.Nullable<int> _CountT;
		
		public sp_teacherIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountT", DbType="Int")]
		public System.Nullable<int> CountT
		{
			get
			{
				return this._CountT;
			}
			set
			{
				if ((this._CountT != value))
				{
					this._CountT = value;
				}
			}
		}
	}
	
	public partial class sp_viewQuestionResult
	{
		
		private System.Nullable<int> _No;
		
		private string _Question;
		
		public sp_viewQuestionResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_No", DbType="Int")]
		public System.Nullable<int> No
		{
			get
			{
				return this._No;
			}
			set
			{
				if ((this._No != value))
				{
					this._No = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Question", DbType="NVarChar(80)")]
		public string Question
		{
			get
			{
				return this._Question;
			}
			set
			{
				if ((this._Question != value))
				{
					this._Question = value;
				}
			}
		}
	}
	
	public partial class sp_ViewQuizNoResult
	{
		
		private System.Nullable<int> _No;
		
		private string _Section_Grade;
		
		private string _Section_name;
		
		private string _Question;
		
		private string _Answer;
		
		private string _Choice1;
		
		private string _Choice2;
		
		private string _Choice3;
		
		private string _T_ID;
		
		public sp_ViewQuizNoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_No", DbType="Int")]
		public System.Nullable<int> No
		{
			get
			{
				return this._No;
			}
			set
			{
				if ((this._No != value))
				{
					this._No = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section_Grade", DbType="VarChar(30)")]
		public string Section_Grade
		{
			get
			{
				return this._Section_Grade;
			}
			set
			{
				if ((this._Section_Grade != value))
				{
					this._Section_Grade = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section_name", DbType="VarChar(30)")]
		public string Section_name
		{
			get
			{
				return this._Section_name;
			}
			set
			{
				if ((this._Section_name != value))
				{
					this._Section_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Question", DbType="NVarChar(80)")]
		public string Question
		{
			get
			{
				return this._Question;
			}
			set
			{
				if ((this._Question != value))
				{
					this._Question = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Answer", DbType="NVarChar(80)")]
		public string Answer
		{
			get
			{
				return this._Answer;
			}
			set
			{
				if ((this._Answer != value))
				{
					this._Answer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Choice1", DbType="NVarChar(80)")]
		public string Choice1
		{
			get
			{
				return this._Choice1;
			}
			set
			{
				if ((this._Choice1 != value))
				{
					this._Choice1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Choice2", DbType="NVarChar(80)")]
		public string Choice2
		{
			get
			{
				return this._Choice2;
			}
			set
			{
				if ((this._Choice2 != value))
				{
					this._Choice2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Choice3", DbType="NVarChar(80)")]
		public string Choice3
		{
			get
			{
				return this._Choice3;
			}
			set
			{
				if ((this._Choice3 != value))
				{
					this._Choice3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_ID", DbType="VarChar(30)")]
		public string T_ID
		{
			get
			{
				return this._T_ID;
			}
			set
			{
				if ((this._T_ID != value))
				{
					this._T_ID = value;
				}
			}
		}
	}
	
	public partial class sp_viewScoreResult
	{
		
		private string _Lastname;
		
		private string _Firstname;
		
		private string _Correct;
		
		private string _Wrong;
		
		public sp_viewScoreResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lastname", DbType="NVarChar(30)")]
		public string Lastname
		{
			get
			{
				return this._Lastname;
			}
			set
			{
				if ((this._Lastname != value))
				{
					this._Lastname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Firstname", DbType="NVarChar(30)")]
		public string Firstname
		{
			get
			{
				return this._Firstname;
			}
			set
			{
				if ((this._Firstname != value))
				{
					this._Firstname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correct", DbType="VarChar(30)")]
		public string Correct
		{
			get
			{
				return this._Correct;
			}
			set
			{
				if ((this._Correct != value))
				{
					this._Correct = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wrong", DbType="VarChar(30)")]
		public string Wrong
		{
			get
			{
				return this._Wrong;
			}
			set
			{
				if ((this._Wrong != value))
				{
					this._Wrong = value;
				}
			}
		}
	}
	
	public partial class sp_viewSectionResult
	{
		
		private string _Section;
		
		private string _Grade;
		
		private string _Teacher;
		
		public sp_viewSectionResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section", DbType="VarChar(30)")]
		public string Section
		{
			get
			{
				return this._Section;
			}
			set
			{
				if ((this._Section != value))
				{
					this._Section = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Grade", DbType="VarChar(30)")]
		public string Grade
		{
			get
			{
				return this._Grade;
			}
			set
			{
				if ((this._Grade != value))
				{
					this._Grade = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Teacher", DbType="VarChar(30)")]
		public string Teacher
		{
			get
			{
				return this._Teacher;
			}
			set
			{
				if ((this._Teacher != value))
				{
					this._Teacher = value;
				}
			}
		}
	}
	
	public partial class sp_viewStudentResult
	{
		
		private string _Lastname;
		
		private string _Firstname;
		
		private string _Section;
		
		private string _Grade;
		
		public sp_viewStudentResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lastname", DbType="NVarChar(30)")]
		public string Lastname
		{
			get
			{
				return this._Lastname;
			}
			set
			{
				if ((this._Lastname != value))
				{
					this._Lastname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Firstname", DbType="NVarChar(30)")]
		public string Firstname
		{
			get
			{
				return this._Firstname;
			}
			set
			{
				if ((this._Firstname != value))
				{
					this._Firstname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section", DbType="VarChar(30)")]
		public string Section
		{
			get
			{
				return this._Section;
			}
			set
			{
				if ((this._Section != value))
				{
					this._Section = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Grade", DbType="VarChar(30)")]
		public string Grade
		{
			get
			{
				return this._Grade;
			}
			set
			{
				if ((this._Grade != value))
				{
					this._Grade = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
